image: Visual Studio 2019

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
build:
  project: jsreport.AspNetCore.sln
before_build:
  - cmd: dotnet restore
artifacts:
- path: jsreport.AspNetCore\bin\Debug\s.jsreport.AspNetCore.*.nupkg
deploy:
- provider: NuGet
  server: NuGet.org
  api_key:
    secure: ieVLsY+sdD7Yq8BMHgvOyPEqQYlhViRSr4abOcqjWHntMx5YauzUAnF9jkuPgSLP
  on:
    branch: master
test_script:
- cd jsreport.AspNetCore.Test
- dotnet test    
